name: Create version
run-name: Creating new version ${{ github.event.inputs.versionType }} by ${{github.actor}}

on:
  workflow_dispatch:
    inputs:
        versionType:
          description: Version type
          required: true
          default: 'patch'
          type: choice
          options:
            - patch
            - minor
            - major
            - premajor
            - preminor
            - prepatch
            - prerelease


jobs:
  create-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate new version ${{ github.event.inputs.versionType }}
        run: |
          npm version ${{ github.event.inputs.versionType }}

      - name: Push the tags
        run: git push origin main --tags
